-- =========================================
-- CREATE OBJECTS - TB_CLIENTE
-- =========================================

-- 1. TABELA
CREATE TABLE TB_CLIENTE (
    ID_CLIENTE        NUMBER(10)         NOT NULL,
    NOME              VARCHAR2(150)      NOT NULL,
    EMAIL             VARCHAR2(150),
    CEP               VARCHAR2(8),
    LOGRADOURO        VARCHAR2(200),
    BAIRRO            VARCHAR2(100),
    CIDADE            VARCHAR2(100),
    UF                CHAR(2),
    ATIVO             NUMBER(1) DEFAULT 1 NOT NULL,
    DT_CRIACAO        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO    TIMESTAMP
);

-- 2. CONSTRAINTS

ALTER TABLE TB_CLIENTE ADD CONSTRAINT PK_TB_CLIENTE 
PRIMARY KEY (ID_CLIENTE);

ALTER TABLE TB_CLIENTE ADD CONSTRAINT UK_TB_CLIENTE_EMAIL 
UNIQUE (EMAIL);

ALTER TABLE TB_CLIENTE ADD CONSTRAINT CK_TB_CLIENTE_UF 
CHECK (UF IN (
'AC','AL','AP','AM','BA','CE','DF','ES','GO',
'MA','MT','MS','MG','PA','PB','PR','PE','PI',
'RJ','RN','RS','RO','RR','SC','SP','SE','TO'
));

ALTER TABLE TB_CLIENTE ADD CONSTRAINT CK_TB_CLIENTE_ATIVO
CHECK (ATIVO IN (0,1));

-- 3. SEQUENCE
CREATE SEQUENCE SEQ_CLIENTE
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 4. TRIGGER BEFORE INSERT
CREATE OR REPLACE TRIGGER TRG_CLIENTE_BI
BEFORE INSERT ON TB_CLIENTE
FOR EACH ROW
BEGIN
    IF :NEW.ID_CLIENTE IS NULL THEN
        SELECT SEQ_CLIENTE.NEXTVAL
        INTO   :NEW.ID_CLIENTE
        FROM   DUAL;
    END IF;

    IF :NEW.DT_CRIACAO IS NULL THEN
        :NEW.DT_CRIACAO := SYSTIMESTAMP;
    END IF;
END;
/

-- 5. TRIGGER BEFORE UPDATE (boa prática)
CREATE OR REPLACE TRIGGER TRG_CLIENTE_BU
BEFORE UPDATE ON TB_CLIENTE
FOR EACH ROW
BEGIN
    :NEW.DT_ATUALIZACAO := SYSTIMESTAMP;
END;
/