CONN SYSTEM/ORACLE@XE;

ALTER SESSION SET CONTAINER = XEPDB1;

DROP USER DEVAPP CASCADE;

CREATE USER DEVAPP
IDENTIFIED BY dev123
DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO DEVAPP;
GRANT RESOURCE TO DEVAPP;
GRANT CONNECT TO DEVAPP;
GRANT DBA TO DEVAPP; 
/

